# Generated by Django 3.1.5 on 2021-03-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shirts',
            new_name='Shirt',
        ),
    ]
