# Generated by Django 3.1.5 on 2021-03-24 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210324_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
