# Generated by Django 3.1.5 on 2021-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shirt_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='sale_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=3),
        ),
    ]
