# Generated by Django 3.1.5 on 2021-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210328_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='shirt_color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black')], default='White', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shirt',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
